DX-2173 TS to JS
Bandwidth-Samples/voice-gather-ts pull request #4
Opened 2021-09-07 14:53 UTC by ckoegel

2021-09-07 19:48 UTC, hamermike requested changes

2021-09-07 19:48 UTC, hamermike commented on package.json
>    "license": "ISC",
```suggestion
  "license": "MIT",
```

2021-09-07 19:48 UTC, hamermike commented on app.js
> +    pplicationId: ${applicationId}
```suggestion
    applicationId: ${applicationId}
```

2021-09-07 20:00 UTC, ajrice6713 approved these changes

2021-09-08 14:48 UTC, hamermike approved these changes

2021-09-08 15:16 UTC, merged